// ONE colour system for the log console: the rows and the histogram must agree, or the graph is just
// decoration — you can't tell which bar is which line. Both LogsViewer and LogHistogram import from
// here, so a module (or a level) has an identical colour in the list and in the chart.

// Level series, in STACK order (bottom → top of a bar) so the array's adjacent pairs are the pairs
// that actually touch on screen — that is what the CVD check is checking.
// Validated with the dataviz validator against the dark chart surface #020617:
// lightness band 0.48–0.67, chroma floor, adjacent CVD (worst ERR↔WRN ΔE 8.8 deutan / 15.4 tritan),
// normal-vision floor (worst 17.6), contrast ≥3:1 — all PASS. The obvious Tailwind picks fail:
// sky-400 #38bdf8 is off the dark lightness band at L 0.754, amber-400 #fbbf24 at L 0.837, and
// slate-500 #64748b reads gray (chroma 0.041) AND lands ΔE 11.6 from the blue for normal vision.
export const LEVEL_SERIES = [
  { key: "dbg", label: "DBG", color: "#b54d98", min: 0 },
  { key: "inf", label: "INF", color: "#2f8fd0", min: 30 },
  { key: "wrn", label: "WRN", color: "#bb881a", min: 40 },
  { key: "err", label: "ERR", color: "#d03b3b", min: 50 },
] as const;

export type LevelKey = (typeof LEVEL_SERIES)[number]["key"];

/** Which of the four chart series a raw pino level belongs to. */
export const levelKey = (level: number): LevelKey =>
  level >= 50 ? "err" : level >= 40 ? "wrn" : level >= 30 ? "inf" : "dbg";

export const levelColor = (level: number): string =>
  LEVEL_SERIES.find((s) => s.key === levelKey(level))!.color;

// Colour per module so the eye can group rows in the All view, and so a stacked bar segment is
// recognisably the same service as the rows under it.
// GENERATED by rotating hue, not a hardcoded list: the number of services is open-ended (gce_instance,
// ai, capacity, ssryeschefc572a, bigquery_*, metric, project, …) and a fixed list either runs out or
// repeats. A fixed 8 did both — everything past the eighth collapsed to the same grey, which is why
// several rows looked identical.
//
// Two constraints shape the rotation:
//  • RESERVED BANDS. Hue is confined to 65°–335°, which excludes red (~0°) and amber (~45°) — those are
//    ERR and WRN. A module drawing red made its INF lines read as errors.
//  • SEPARATION. Successive hues step by the golden angle inside that 270° span, so each new module
//    lands as far as possible from the ones already assigned, and lightness alternates between two
//    steps so even a near-hue pair differs on a second axis. Both steps stay inside the dark band
//    (L≈0.55/0.68 → contrast ≥3:1 on #020617); the ±10% keeps them clear of the light end that made
//    the old hsl(h,65%,68%) generator fail validation for greens and yellows.
// The golden RATIO applied to a unit interval, then mapped into the span — not a 137.5° step taken
// modulo the span. Stepping degrees mod 270 wraps onto itself every other index (0°, 137.5°, 5°,
// 142.5°, 10°…), which put ssryeschefc572a and bigquery_resource on the same yellow-green and three
// services on the same blue. `(i * φ⁻¹) mod 1` is a low-discrepancy sequence: every new index lands in
// the largest remaining gap, so separation degrades gracefully instead of colliding.

// The Map is module-scoped on purpose: it is the shared assignment ledger, so both call sites get the
// same colour for the same name regardless of which one asked first, and a filter that changes how many
// modules are on screen never repaints the survivors.
const slots = new Map<string, number>();
const slotOf = (name: string): number => {
  if (!slots.has(name)) slots.set(name, slots.size);
  return slots.get(name)!;
};

/** Every module gets a real colour now — nothing folds into a shared neutral. */
export const hasColorSlot = (_name?: string): boolean => true;

export const componentColor = (name?: string): string => {
  const i = slotOf(name || "?");
  // Constants are INLINE, not module-scope. A renamed module-level const survives a Vite transform
  // check and only explodes at runtime (`GOLDEN is not defined`), and a browser holding any older copy
  // of this module hits the same wall. Nothing here can reference a binding that isn't in the function.
  const hue = (65 + (((i * 0.6180339887) % 1) * 270)).toFixed(1);
  // Lightness cycles on THREE steps, not two. Hue collisions come from indices that are far apart (the
  // low-discrepancy sequence fills gaps), and a 2-cycle lands those on the same lightness — measured, a
  // 2-cycle's worst pair was 15° apart with identical lightness, a 3-cycle's is 9° apart with 12% of
  // lightness between them, which more than doubles the worst-case separation.
  return `hsl(${hue}, 68%, ${[68, 56, 44][i % 3]}%)`;
};

// Kept for the chart's "other" bucket label; no longer used as a colour fallback.
export const OTHER_KEY = "…other";
export const OTHER_COLOR = "#64748b";

